# Generated by Django 3.1.7 on 2021-10-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessages',
            old_name='description',
            new_name='projectsummary',
        ),
    ]
